/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#e3e2de',
        'surface-container-highest': '#e3e2e0',
        'primary-fixed': '#d1e8d5',
        'on-tertiary-fixed-variant': '#404942',
        'on-secondary-fixed-variant': '#464744',
        'surface-container-low': '#f4f3f1',
        'on-tertiary-fixed': '#151e17',
        tertiary: '#4f5951',
        'on-secondary-container': '#626360',
        'inverse-on-surface': '#f2f1ef',
        'on-primary-container': '#e2f9e5',
        'on-surface-variant': '#434843',
        'on-primary-fixed': '#0c1f13',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#ecf6eb',
        'on-primary': '#ffffff',
        background: '#faf9f7',
        surface: '#faf9f7',
        'surface-container-high': '#e9e8e6',
        'on-error-container': '#93000a',
        'outline-variant': '#c3c8c1',
        'tertiary-fixed-dim': '#bfc9bf',
        'on-background': '#1a1c1b',
        'on-tertiary': '#ffffff',
        'on-surface': '#1a1c1b',
        'surface-bright': '#faf9f7',
        'tertiary-container': '#687169',
        'on-primary-fixed-variant': '#374b3d',
        'primary-container': '#5f7464',
        'primary-fixed-dim': '#b5ccb9',
        'secondary-container': '#e1e0dc',
        'on-secondary-fixed': '#1b1c1a',
        secondary: '#5e5f5c',
        primary: '#475b4c',
        'error-container': '#ffdad6',
        'surface-dim': '#dbdad8',
        'inverse-primary': '#b5ccb9',
        'surface-tint': '#4f6354',
        'secondary-fixed-dim': '#c7c6c3',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'surface-container': '#efeeec',
        'inverse-surface': '#2f3130',
        'surface-variant': '#e3e2e0',
        error: '#ba1a1a',
        'tertiary-fixed': '#dbe5db',
        outline: '#737873',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'margin-desktop': '64px',
        base: '8px',
        'margin-mobile': '16px',
        'container-max': '1200px',
        'section-gap': '80px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Literata'],
        'headline-lg': ['Literata'],
        'body-lg': ['Metropolis'],
        'label-md': ['Metropolis'],
        'body-md': ['Metropolis'],
        'headline-sm': ['Literata'],
        'headline-md': ['Literata'],
        'label-sm': ['Metropolis'],
      },
      fontSize: {
        'headline-lg-mobile': [
          '32px',
          { lineHeight: '1.2', fontWeight: '600' },
        ],
        'headline-lg': [
          '48px',
          { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': [
          '14px',
          { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1', fontWeight: '500' }],
      },
    },
  },
};
